CREATE TABLE IF NOT EXISTS products(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    category text,
    price INTEGER NOT NULL,
    quantity integer
);
CREATE TABLE IF NOT EXISTS categories(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECk (name <> ''),
    categoryId INTEGER REFERENCES products(id)
);
/* Values products */
INSERT INTO products(name, category, price, quantity)
VALUES('Motorola G9 plus', 'smartphone', 900000, 5);

INSERT INTO products(name, category, price, quantity)
VALUES('Iphone X', 'smartphone', 2900000, 15);

INSERT INTO products(name, category, price, quantity)
VALUES('Imac 27 inches - 2020', 'Computer', 7245000, 3);

/* Values category */
INSERT INTO categories(name, categoryId)
VALUES ('smartphone', 1);

INSERT INTO categories(name, categoryId)
VALUES ('smartphone', 2);

INSERT INTO categories(name, categoryId)
VALUES ('Computer', 3);