create database product;
-- List databases
\l

-- connect or use the database
\c product

CREATE TABLE IF NOT EXISTS products(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    category text,
    price INTEGER NOT NULL,
    quantity integer
);

-- list tables
\dt

-- describe table
\d products


/* Values products */
INSERT INTO products(name, category, price, quantity)
VALUES('Motorola G9 plus', 'smartphone', 900000, 5);

INSERT INTO products(name, category, price, quantity)
VALUES('Iphone X', 'smartphone', 2900000, 15);

INSERT INTO products(name, category, price, quantity)
VALUES('Imac 27 inches - 2020', 'Computer', 7245000, 3);

-- list data
select * from products;